### ISSUE TITLE
Field Reason in messages

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/golem-messages#10]
In many messages in documentation 
https://docs.google.com/document/d/1QMnamlNnKxichfPZvBDIcFm1q0uJHMHJPkCt24KElxc/view?pli=1#heading=h.dhlbf3h55z2u
there is a field Reason. Add Reason to the message MessageRejectReportComputedTask. Decide what is the best way to keep it: enum, stings, dictionary. Take into account existing structures in such messages as MessageCannotComputeTask, MessageTaskFailure, maybe others. Apply this decision to existing messages like MessageCannotComputeTask, MessageTaskFailure, MessageSubtaskResultsRejected according to the documentation. Reason options that do not yet exist need no new logic.

**Comment by jiivan** [comment]
I think it should be simple string. Eventually a frozenset of allowed reason values may be used.
A simple string is readable and easy to understand and debug.

Using dict (or any other custom mapping such as enum) only adds unnecessary middle layer, and is consequently less readable. The msg size benefit is negligible in context of potential resources size and minimal amount of such messages.

**Comment by etam** [comment]
@jiivan Using enum in python is quite readable.

If you have
```python
class MyEnum(Enum):
  A = 1
  B = 2
  C = 3
```

Then, when debugging, you'll see not just a numeric value, but an object representation like this:

```<MyEnum.A: 1>```

Also, if while deserializing input, there is an illegal value, enum constructor will throw an exception. For a set of strings you'll need to manually check the value. It's not a big problem (just a line or two), but still something to care about.

So I'm not convinced, that using an enum is less readable.

**Comment by jiivan** [comment]
@etam good point, but it still doesn't address magic numbers issue. What I mean is that for example in logs/wireshark etc we can see:

```python
>>> from golem_messages import message
>>> m = message.MessageDisconnect()  # numerical magic number
>>> m.serialize(lambda x: b'*'*message.Message.SIG_LEN)
b'\x00\x02\x00\x05^\x1c\xb6\xf2\xf3&\x00*****************************************************************\xd8\x1c\x81\xd8\x1c\x82freason '
```

I think this is easier to debug:
```python
>>> m = message.MessageDisconnect('TooManyPeers')  # Descriptive label
>>> m.serialize(lambda x: b'*'*message.Message.SIG_LEN)
b'\x00\x02\x00\x05^\x1c\xb9%\xf3I\x00*****************************************************************\xd8\x1c\x81\xd8\x1c\x82freasonlTooManyPeers`
```

Can we find a solution that avoids *magic numbers* and also enforces *valid values*?

**Comment by cameel** [comment]
Python `Enum`s can have arbitrary values, not just ints:
``` python
class MyEnum(Enum):
    A = 'ReasonA'
    B = 'Reason B'
    C = 'NOT_A_GOOD_REASON'
    D = 4
    E = None
```

**Comment by jiivan** [comment]
Still why use any mapping/enum if we only care about values from strictly defined set?

**Comment by etam** [comment]
Because I'd like to have in code `if reason == MyEnum.A:` than `if reason == "some string:"`. This way I can find, refactor or statically check values using more sophisticated tools than grep.
