### ISSUE TITLE
add a "Concent Enabled" flag to `TaskToCompute`

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/golem-messages#125]
+ add reason to `Service Refused`

**Comment by jiivan** [comment]
Actually creating a property `TaskToCompute.concent_enabled` would be enough.

**Comment by cameel** [comment]
Is Concent supposed to take the value of this flag into account?

**Comment by jiivan** [comment]
@cameel good catch :) Yes, ideally golem won't send TTC with concent disabled, but concent should verify that it's set to True.

**Comment by cameel** [comment]
OK. So I assume that Concent should respond with `ServiceRefused` if the flag is false, right? If that's the case then we need the corresponding refusal reason in the spec (paging @lukasz-glen).

Though I wonder if it's really good for the users to enforce it. Before this change just creating a task did not force anyone to go to Concent but still gave them that option. But with this flag, setting it to false creates a situation where parties cannot later decide to use Concent even if they have deposits. Is there any gain for a honest provider or requestor in knowing that problems cannot be arbitrated through Concent?
