### ISSUE TITLE
Missing ForceSubtaskResults and ForceSubtaskResultsResponse in message/__init__.py

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/golem-messages#132]
ForceSubtaskResults and ForceSubtaskResultsResponse are not being added to `registered_message_types`

**Comment by jiivan** [comment]
It shouldn't. Old messages are imported only for backwards compatibility. New code should reference messages directly: `message.concents.ForceSubtaskResults`

**Comment by jiivan** [comment]
Reopenning after talk with @shadeofblue . The problem is not with import, but with `registered_message_types`

**Comment by rwrzesien** [comment]
@jiivan @shadeofblue Added info about missing ForceSubtaskResultsResponse too.
