### ISSUE TITLE
Client eth address is not available when ForceSubtaskResults communication starts

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/golem-messages#147]
To check if client has enough amount on his deposit to pay for communication fee when communication starts, we need his eth address. It is currently available in ForceSubtaskResults message. However, when communication related to ForceSubtaskResults case starts, there is no ForceSubtaskResults message inside it or inside nested messages, so there is no possibility to get eth address.

**Comment by lukasz-glen** [comment]
clarification: communication fee has nothing to deposits

**Comment by rwrzesien** [comment]
Closed after discussion, eth address will come from TaskToCompute, not from ReportComputedTask.
