### ISSUE TITLE
Call Concent to force MessageReportComputedTask

### ISSUE THREAD

**Issue by lukasz-glen** [golemfactory/golem-messages#16]
Implement behavior of Provider: Provider calls Concent to force MessageReportComputedTask if Requestor is do not respond with MessageAckReportComputedTask. Provider has to do it with respect to time windows. 
Implementing Requestor side and receiving from Concent is not part of this issue.
See documentation:
https://docs.google.com/document/d/1QMnamlNnKxichfPZvBDIcFm1q0uJHMHJPkCt24KElxc/edit?pli=1#heading=h.7exgi6n6wexp
Part of this issue is to implement first call to Concent, it should be done with care and generalization in mind.

**Comment by lukasz-glen** [comment]
that issue should be in golem repo, sigh

**Comment by maaktweluit** [comment]
@lukasz-glen as far as i know there is no way to move issues, best is to close this and re-create it in golem. want me to pick it up if you are traveling?

**Comment by jiivan** [comment]
Resolved in https://github.com/golemfactory/golem/pull/1699
