### ISSUE TITLE
Add Concent constants to golem-messages

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/golem-messages#196]

**Comment by cameel** [comment]
Constants currently defined in Concent:

``` python
CONCENT_MESSAGING_TIME    = 3600
FORCE_ACCEPTANCE_TIME     = 3600 * 4
MAXIMUM_DOWNLOAD_TIME     = 1800
SUBTASK_VERIFICATION_TIME = 3600 * 4
PAYMENT_DUE_TIME          = 3600 * 12
```

Note that [maximum_download_time()](https://github.com/golemfactory/golem-messages/blob/v2.3.4/golem_messages/helpers.py#L23-L39) is a constant in Concent but not in golem-messages. We're going to change that in Concent.
