### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by Elfoniok** [golemfactory/golem-messages#2]
We need CI for this.

**Comment by cameel** [comment]
What CI are you using in the rest of Golem? CircleCI?

**Comment by maaktweluit** [comment]
We use:
- Buildbot ( all are migrated here in the future )
- CircleCI ( linux )
- Appveyor ( windows )
- Travix ( MacOS )
- Shippable ( lint on linux )

I recommend using CircleCI for now, its the most pleasant / stable of the list above.
