### ISSUE TITLE
Implement symmetric cryptography for sessions

### ISSUE THREAD

**Issue by badb** [golemfactory/golem-messages#203]
Right now we encrypt everything using asymetric elliptic curves based cryptography. It makes message parsing and interpreting too slow. We would like to keep asymmetric cryptography in hello messages but then when the identity of node is confirmed we want to use symmetric encryption for the rest of the session.

**Comment by lukasz-glen** [comment]
But messages still should be signed with asymmetric cryptography, with private key that identifies node. Otherwise things get complicated with Concent.

**Comment by Wiezzel** [comment]
@lukasz-glen Which types of messages are important for consent? I believe we can still use symmetric encryption for those which aren't.

**Comment by mfranciszkiewicz** [comment]
@Wiezzel I think he only meant digital signatures, not encryption. Messages are sent to Concent unencrypted.

**Comment by badb** [comment]
To sum up:
* task related messages should be signed with asymmetric cryptography (just like know)
* p2p related messages may not be necessarily signed (just task related ones, ie. sending task headers, removing tasks)
* asymmetric cryptography should also be used at the beginning of the session to confirm sites identity and negotiate keys that are going to be used to encrypt further communication
* further communication can be done using symmetric cryptography

**Comment by Wiezzel** [comment]
@badb What is the approx. desired duration of message serialization/deserialization?

**Comment by badb** [comment]
0.1 millisecond for full message parsing, with deserialization included, would be great (for now)

**Comment by Wiezzel** [comment]
Closed by https://github.com/golemfactory/golem-messages/pull/219
