### ISSUE TITLE
Remove message signing when it's not necessary

### ISSUE THREAD

**Issue by badb** [golemfactory/golem-messages#204]
Most task session related messages must be signed so we can make sure that it can be used with Concent. Same applies with RemoveTask message & TaskHeaders, when requestor must prove his/her claims towards specific task. But for the rest of p2p related messages it's just enough to confirm identity when we start session. Additional information about peers or just external messages about tasks don't need to be confirmed.

**Comment by Wiezzel** [comment]
Closed by https://github.com/golemfactory/golem-messages/pull/219
