### ISSUE TITLE
ReportComputedTask's EXPECTED_OWNERS are missing requestor

### ISSUE THREAD

**Issue by rwrzesien** [golemfactory/golem-messages#238]
Currently in `ReportComputedTask.EXPECTED_OWNERS` there is only provider, however when Concent receives `AckReportComputedTask` it validates if nested `ReportComputedTask` is signed by requestor. This blocks from switching to use of `validate_ownership` in Concent.

**Comment by rwrzesien** [comment]
After discussion I am closing this as invalid.

**Comment by cameel** [comment]
@rwrzesien It would be a good idea to summarize the discussion when closing the issue.

We're closing it because `ReportComputedTask` should indeed by signed by the provider. For some reason we started thinking that it should be the requestor but that was a mistake on our part.
