### ISSUE TITLE
Unnecessary concent field in TTC

### ISSUE THREAD

**Issue by Krigpl** [golemfactory/golem-messages#311]
https://github.com/golemfactory/golem-messages/blob/master/golem_messages/message/tasks.py#L294
This has exactly the same value as `WantToComputeTask` which is included in TTC so it doesn't seem useful.

**Comment by shadeofblue** [comment]
okay, that it has the same value as `WantToComputeTask` is an implementation choice, not a protocol property - we should still be able to clearly state that a subtask has concent enabled and this property is the final effect of any negotiation prior to creation of the `TaskToCompute` message.

if we e.g. wanted to enable the providers to still _want_ to compute tasks with Concent but also optionally accept tasks without Concent, this could cause us to break the direct mapping between `WTCT.concent_enabled` and `TaskToCompute.concent_enabled`
