### ISSUE TITLE
add a child slot for `ForceGetTaskResultFailed` in SubtaskResultsRejected

### ISSUE THREAD

**Issue by shadeofblue** [golemfactory/golem-messages#346]
According to the Concent specs, in case the Concent fails to retrieve the results in UC2, it issues a `ForceGetTaskResultFailed` message to the Requestor.

In UC3, the Requestor should be able to utilize that message to send a `SubtaskResultsRejected` with `ForcedResourcesFailure` reason and attach the `ForceGetTaskResultFailed` message

We need to:
* add an optional `force_get_task_result_failed` slot to `SubtaskResultsRejected`
* enforce that this slot is a `ForceGetTaskResultFailed`

**Comment by Krigpl** [comment]
What does the requestor need the `ForceGetTaskResultFailed` message for?

**Comment by shadeofblue** [comment]
@Krigpl so that it can prove to the Provider (and to the Concent) that it tried to download the results through Concent but failed
