### ISSUE TITLE
Catching DescryptionError in message.py

### ISSUE THREAD

**Issue by kbeker** [golemfactory/golem-messages#52]
When we use `load()` method and we give wrong message we should get exception DescriptionError from golem_message. For this moment golem_messages doesn't catch this exception and goes on. After finish
`msg = message.Message.deserialize(data, decrypt, check_time)`

it continue its work and throw exception `AttributeError: 'NoneType' object has no attribute 'sig'` on next method inside `load()`:

`cryptography.ecdsa_verify(pubkey, msg.sig, msg.get_short_hash())`

but it should throw exception in `message.py`

```
except Exception as exc:
            logger.info("Message error: invalid data: %r", exc)
            logger.debug("Failing message hdr: %r data: %r", header, data)
            return
```

Above is place where this exception should be thrown.

**Comment by jiivan** [comment]
I am also proponent of raising some kind of exception in this situation. Unfortunately it's more labor intensive than it may seem at first sight. All golem core codebase expects `None` after failed _deserialization_ and also lot of tests (both in golem core and golem-messages).

Still I second to that idea and hope to implement it in a near future.
