### ISSUE TITLE
File transfer token for Concent

### ISSUE THREAD

**Issue by cameel** [golemfactory/golem-messages#53]
Concent needs a special type of message to use as a token (as proposed in https://github.com/golemfactory/concent-deployment/issues/18). I see that messages types are hard-coded in `init_messages()` so we need to add it to golem-messages to support decoding and encoding it.

I think a good name for this message would be `FileTransferToken`.

We can submit a pull request with the implementation and work on resolving potential issues. Or we can leave implementation to the Golem team.

### Message payload
Here's the initial proposal based on what Concent needs. Golem will not have to decode this message (it can use it transparently, as a token) but comments on how to make it useful to the client are welcome. This is just a starting point for discussion:

| field                                  | type                                             | description |
|----------------------------------------|--------------------------------------------------|-------------|
| `token_expiration_deadline`            | int (UNIX timestamp)                             | The timestamp that determines the maximum time to sumit the token. After that point in time the gatekeeper unconditionally rejects the token as invalid.
| `storage_cluster_address`              | string (relative URL)                            | The address of the cluster that stores files. Must be a file (not ending with `/`) and not contain `/../` sections.
| `authorized_client_public_key`         | bytes (ECDSA public key)                         | Public key of the Golem client authorized to transfer the files.
| `operation`                            | string (`'upload'` or `'download'`)              | The operation the client is authorized to perform.
| `files`                                | list of `datastructures.FrozenDict` `(FileInfo`) | The list of files the client is authorized to transfer and their metadata.

#### `FileInfo` dict

| field      | type                    | description |
|------------|-------------------------|-------------|
| `path`     | string (relative path)  | Path, relative to a directory defined in server configuration.
| `size`     | int                     | File size in bytes.
| `checksum` | string        | Hash of the content of the file. Consists of two parts joined with a colon: the type of the checksum and the hash.

Remarks:
- I'm assuming that we're identifying the client by its public key. This also is probably not how it's going to be done eventually but we're using it for the time being until we agree with Łukasz on how this should be done.

### Example

``` python
{
    'timestamp':                    1510410600, # 2017-11-11 15:30
    'token_expiration_deadline':    1510412400, # 2017-11-11 16:00
    'cluster_address':              "http://storage.concent.golem.network/",
    'authorized_client_public_key': 'cHJvdmlkZXIgcHVibGljIGtleSAxMjM0NTY',
    'operation':                    'upload',
    'files':                        [
        {
            'path':     'blender/2/result.tiff',
            'checksum': 'sha1:2bebc22296f03225617704d29d277c9e96fafcc2',
            'size':     1048576,  # bytes
        },
    ],
}
```

**Comment by cameel** [comment]
Token spec updated according to @jiivan's remarks from https://github.com/golemfactory/golem-messages/pull/57#discussion_r158942318

`files` changed to a list od `datastructures.FrozenDict`

### Previous spec
Here's the old version for reference:

| field      | type                    | description |
|------------|-------------------------|-------------|
| `files`                                | list of string (list of relative paths) | The list of files the client is authorized to transfer. Relative to a directory defined in server configuration.
| `file_sizes`                           | list of int                             | The list of sizes corresponding to the files in `files`.
| `md5_hashes`                           | list of string (list of MD5 hashes)     | The list of MD5 hashes corresponding to the content of files in `files`.

``` python
    'files':                        [
        'blender/2/result.tiff',
    ],
    'file_sizes': {
        1048576,  # bytes
    },
    'md5_hashes': {
        '098f6bcd4621d373cade4e832627b4f6',
    },
```

**Comment by cameel** [comment]
@jiivan Which algorithm is currently used for file checksums in Golem? Or do you use some prefix to indicate the type of the hash? Could you give me an example of a real golem message or any type that contains a fil hash?

**Comment by jiivan** [comment]
@cameel This is my proposal: https://github.com/golemfactory/golem/pull/1823/files#diff-88ebb160824a1d131d3a3cd84874e290R459
It can be changed if needed

**Comment by cameel** [comment]
OK, so something like `'sha1:2bebc22296f03225617704d29d277c9e96fafcc2'`? Seems fine to me.

**Comment by cameel** [comment]
Description updated to use hashes like the above instead of MD5.

**Comment by Jakub89** [comment]
@jiivan There is a problem with using `datastructures.FrozenDict` with our token. It produce un-deterministic errors `golem_messages.exceptions.InvalidSignature`. One idea is that dict changes the order of those three values. Also that bug appear when tested on Python 3.5.2, but disappear with new 3.6.
Script we use for testing:
```
import datetime

from golem_messages.shortcuts       import dump, load
from golem_messages.message         import FileTransferToken, TokenFilesData


CONCENT_PUBLIC_KEY  = b'\xf3\x97\x19\xcdX\xda\x86tiP\x1c&\xd39M\x9e\xa4\xddb\x89\xb5,]O\xd5cR\x84\xb85\xed\xc9\xa17e,\xb2s\xeb\n1\xcaN.l\xba\xc3\xb7\xc2\xba\xff\xabN\xde\xb3\x0b\xa6l\xbf6o\x81\xe0;'
CONCENT_PRIVATE_KEY = b'l\xcdh\x19\xeb$>\xbcG\xa1\xc7v\xe8\xd7o\x0c\xbf\x0e\x0fM\x89lw\x1e\xd7K\xd6Hnv$\xa2'

message_timestamp = 1546171200
token                                 = FileTransferToken(timestamp=message_timestamp)
token.token_expiration_deadline       = message_timestamp + 3600
token.storage_cluster_address         = 'http://storage.concent.golem.network/'
token.authorized_client_public_key    = b'\xf3\x97\x19\xcdX\xda\x86tiP\x1c&\xd39M\x9e\xa4\xddb\x89\xb5,]O\xd5cR\x84\xb85\xed\xc9\xa17e,\xb2s\xeb\n1\xcaN.l\xba\xc3\xb7\xc2\xba\xff\xabN\xde\xb3\x0b\xa6l\xbf6o\x81\xe0;'

token.files             = TokenFilesData()
token.files['path']     = 'blender/benchmark/test_task/scene-Helicopter-27-cycles.blend'
token.files['checksum'] = '098f6bcd4621d373cade4e832627b4f6'
token.files['size']     = 1024
token.operation         = 'download'

serialize_token = dump(token, CONCENT_PRIVATE_KEY, CONCENT_PUBLIC_KEY)

loaded_golem_message = load(serialize_token, CONCENT_PRIVATE_KEY, CONCENT_PUBLIC_KEY, check_time = False)
```
golem.messages version:
-e git+git@github.com:Code-Poets/golem-messages.git@434ea988aeb83ed0976c55685245e213f2f65c1a#egg=Golem_Messages

**Comment by cameel** [comment]
@Jakub89 I think this should be reported in a separate issue.
