### ISSUE TITLE
MessageTaskToCompute is not fully defined

### ISSUE THREAD

**Issue by cameel** [golemfactory/golem-messages#6]
The comments in the definition of `MessageTaskToCompute` refer to `ComputeTaskDef` but this class is only defined in [taskbase.py in golem repo](https://github.com/golemfactory/golem/blob/0.9.0/golem/task/taskbase.py#L152-L167). Its definition is needed to fully decode the payload of the message. I think it should be moved to this repository.

**Comment by lukasz-glen** [comment]
Agree.
golem-messages must not have such dependencies.
To be done: check usages of ComputeTaskDef and if there loosely coupled with the rest of the Golem code then move it to golem-messages. If it is tightly coupled then we must figure out how to do it properly.
