### ISSUE TITLE
PYLINT warning

### ISSUE THREAD

**Issue by kbeker** [golemfactory/golem-messages#86]
Before version 1.2.0 of golem_messages PYLINT have never give any warning about this code:
```
from golem_messages.message import WantToComputeTask

def want_to_compute_example():
    want_to_compute = WantToComputeTask()
    want_to_compute.node_name
```
After update to version 1.2.0 there is a need to add to the last line of code ignore statement to disable no-member warning. If we won't add this statement we would get always warning mentioned below.

```
Instance of 'WantToComputeTask' has no 'node_name' member (no-member)
```

**Comment by jiivan** [comment]
Yes, pylint won't discover dynamically set attributes (event though they're defined in `__slots__`). No-member check will be ignored in #81
