### ISSUE TITLE
Storing public keys of requestor and provider in TaskToCompute

### ISSUE THREAD

**Issue by cameel** [golemfactory/golem-messages#90]
According to @lukasz-glen `TaskToCompute` is supposed to contain all the information needed to identify the provider and the requestor. This includes public keys, blockchain addresses, etc. I don't know the full extent of this information but for now we need at least the public keys there to be able to implement proper authentication in Concent. Concent is going to process a message only if it was signed by one of the parties listed in `TaskToCompute`.

**Comment by cameel** [comment]
I see that Łukasz has already created #77 and it has been already implemented. It added only golem IDs though. Unless the IDs are the same as the public keys, we still need the keys in the message.

**Comment by jiivan** [comment]
depends on: #98
